token = "token"
author_id = "id"

[[sources]]
external_javadoc = []
database = "/home/i_al_istannen/src/spoon/JavadocIndexer/target/Jdk-Index.db"
javadoc_url = "https://docs.oracle.com/en/java/javase/19/docs/api"

[[sources]]
external_javadoc = [
    "https://guava.dev/releases/21.0/api/docs/",
    "https://javadoc.io/doc/org.yaml/snakeyaml/1.28/",
    "https://javadoc.io/doc/org.jetbrains/annotations/21.0.1/",
    "https://javadoc.io/doc/net.md-5/bungeecord-chat/1.16-R0.4/",
    "https://jd.adventure.kyori.net/api/4.8.1/",
    "https://jd.adventure.kyori.net/text-serializer-gson/4.8.1/",
    "https://jd.adventure.kyori.net/text-serializer-legacy/4.8.1/",
    "https://jd.adventure.kyori.net/text-serializer-plain/4.8.1/",
    "https://docs.oracle.com/en/java/javase/19/docs/api"
]
database = "/home/i_al_istannen/src/spoon/JavadocIndexer/target/Paper-Api-Index.db"
javadoc_url = "https://papermc.io/javadocs/paper/1.19/"

[[sources]]
external_javadoc = [
    "https://docs.oracle.com/en/java/javase/19/docs/api"
]
database = "/home/i_al_istannen/src/spoon/JavadocIndexer/target/JDA-Index.db"
javadoc_url = "https://ci.dv8tion.net/job/JDA/javadoc/"

[[sources]]
external_javadoc = [
    "https://docs.oracle.com/en/java/javase/19/docs/api"
]
database = "/home/i_al_istannen/src/spoon/JavadocIndexer/target/JavaFx-Index.db"
javadoc_url = "https://openjfx.io/javadoc/16/"

[[sources]]
external_javadoc = [
    "https://docs.oracle.com/en/java/javase/19/docs/api"
]
database = "/home/i_al_istannen/src/spoon/JavadocIndexer/target/ApFloat-Index.db"
javadoc_url = "http://www.apfloat.org/apfloat_java/docs/"
