token = "token"
author_id = "id"

[[sources]]
external_javadoc = []
database = "/home/i_al_istannen/src/spoon/JavadocBpi/target/Jdk-Index.db"
javadoc_url = "https://docs.oracle.com/en/java/javase/19/docs/api/index.html"
